---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - 'https://github.com/rackerlabs/mpk-apps.git/defaults/cert-manager'

patchesStrategicMerge:
    - './crds.yaml'
    - './deployment.yaml'
    - './webhook.yaml'
