---
# Source: harbor-operator/templates/mutatingwebhookconfiguration.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: 'rackspace-staging/harbor-operator-serving-cert'
  name: 'harbor-operator-mutating-webhook-configuration'